version: '3.2'

volumes:
  tmp-data:
  redis-data:

services:
  app:
    image: golang:1.23.0-alpine
    working_dir: /src
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    depends_on:
      - redis
    ports:
      - "8080:8080"
    command: ./app

  redis:
    image: redis:7.4.0-alpine
    volumes:
      - redis-data:/data:cached
    ports:
      - 6379
      - '6379:6379/tcp'
